"""
layers/user.py
==============
User Layer — Personal Overrides (Highest Priority)

Priority: 90 — applied last; wins over every other layer.

══════════════════════════════════════════════════════════════
  ⚠  DO NOT EDIT THIS FILE.
     Configure your qutebrowser by editing the
     CONFIGURATION SECTION and USER PREFERENCE SECTION
     at the top of config.py.
     This file is a data receiver — not a configuration surface.
══════════════════════════════════════════════════════════════

Architecture role:
  config.py (USER PREFERENCE SECTION)
    → _build_orchestrator()
        → UserLayer(editor=..., start_pages=..., zoom=..., ...)
            → _settings()  ← translates injected params to qutebrowser keys
            → _keybindings() / _aliases()

All preferences are injected via the constructor.
The _settings() method is a pure translator — no side effects, no I/O.

search_engines merge semantics:
  By default (search_engines_merge=True), the dict is MERGED on top of
  what lower layers already set — so you only specify additions/overrides.
  Set search_engines_merge=False to REPLACE the entire engine map.

Strict-mode: all params typed; injected collections are defensively copied.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional, Tuple

from core.layer import BaseConfigLayer

ConfigDict  = Dict[str, Any]
BindingList = List[Tuple[str, str, str]]

logger = logging.getLogger("qute.layers.user")


class UserLayer(BaseConfigLayer):
    """
    Personal overrides — final layer applied, highest priority (90).

    All parameters are injected from config.py.
    This class is not intended to be edited by end-users.

    Args:
        leader:              Leader key prefix (default ",").
        editor:              Editor command list, e.g. ["kitty", "-e", "nvim", "{}"].
                             None → keep BaseLayer default.
        start_pages:         List of start page URLs.  None → keep default.
        zoom:                Default zoom level string, e.g. "110%".  None → skip.
        search_engines:      dict[shortcut, url_template].
                             None → keep base layer engines unchanged.
        search_engines_merge:If True (default), merges engines ON TOP of what
                             lower layers set.  If False, replaces entirely.
        spellcheck_langs:    Language codes for spellcheck, e.g. ["en-US"].
                             None → keep base default.
        extra_settings:      Arbitrary additional qutebrowser settings (escape hatch).
        extra_bindings:      Arbitrary additional keybindings [(key, cmd, mode), ...].
        extra_aliases:       Arbitrary additional command aliases {name: command}.
        github_username:     GitHub username for the :gh alias.
    """

    name        = "user"
    priority    = 90
    description = "Personal overrides — highest priority; driven by config.py"

    def __init__(
        self,
        leader:               str                   = ",",
        editor:               Optional[List[str]]   = None,
        start_pages:          Optional[List[str]]   = None,
        zoom:                 Optional[str]         = None,
        search_engines:       Optional[ConfigDict]  = None,
        search_engines_merge: bool                  = True,
        spellcheck_langs:     Optional[List[str]]   = None,
        extra_settings:       Optional[ConfigDict]  = None,
        extra_bindings:       Optional[BindingList] = None,
        extra_aliases:        Optional[ConfigDict]  = None,
        github_username:      str                   = "redskaber",
    ) -> None:
        self._leader               = leader
        self._editor               = editor
        self._start_pages          = start_pages
        self._zoom                 = zoom
        self._search_engines       = dict(search_engines)   if search_engines   else None
        self._search_engines_merge = search_engines_merge
        self._spellcheck_langs     = list(spellcheck_langs) if spellcheck_langs else None
        self._extra_settings       = dict(extra_settings)   if extra_settings   else {}
        self._extra_bindings       = list(extra_bindings)   if extra_bindings   else []
        self._extra_aliases        = dict(extra_aliases)    if extra_aliases    else {}
        self._github_username      = github_username

    def _settings(self) -> ConfigDict:
        settings: ConfigDict = {}

        # ── Editor ────────────────────────────────────────────────────────
        if self._editor is not None:
            settings["editor.command"] = self._editor
            logger.debug("[UserLayer] editor: %s", self._editor)

        # ── Start pages ───────────────────────────────────────────────────
        if self._start_pages is not None:
            settings["url.start_pages"]  = self._start_pages
            settings["url.default_page"] = self._start_pages[0] if self._start_pages else "about:blank"

        # ── Default zoom ──────────────────────────────────────────────────
        if self._zoom is not None:
            settings["zoom.default"] = self._zoom

        # ── Search engines ────────────────────────────────────────────────
        # Merge mode: inject a special "_merge_engines" sentinel key.
        # The orchestrator's apply_settings call writes it to config.set()
        # which will fail, so we use a different approach:
        # We store the engines and a merge flag; the layer system resolves it
        # by priority — for merge semantics we use a deep merge key.
        #
        # Implementation note: since LayerStack uses _deep_merge for dicts,
        # and url.searchengines is a dict, we CAN achieve merge semantics
        # by placing our engines inside the "settings.url.searchengines" dict —
        # but only if we store them as a partial dict and let _deep_merge
        # accumulate them.  The layer already produces a dict value; deep_merge
        # will replace the whole dict (dict → dict merge recurses correctly).
        #
        # To truly merge: we rely on the fact that _deep_merge recurses into
        # nested dicts at depth ≥ 1 (settings dict level), so if both base
        # and user set "url.searchengines" as dicts, they are deep-merged.
        # This means UserLayer only needs to supply its *delta* engines,
        # and the merge happens automatically.
        #
        # For REPLACE semantics: set search_engines_merge=False; in that
        # case we include a special marker key "_replace" that signals
        # downstream to treat this as an override.  Since qutebrowser ignores
        # unknown keys (config.set silently errors), we rely on priority-order:
        # UserLayer at priority=90 wins, so the entire dict value overwrites.
        # That is the existing default behaviour — dict replace at settings level.
        #
        # Summary:
        #   merge=True  → user dict merges on top via _deep_merge recursion ✓
        #   merge=False → user dict replaces (existing LayerStack behaviour) ✓
        if self._search_engines is not None:
            if self._search_engines_merge:
                # Partial dict — _deep_merge will merge it into base engines
                settings["url.searchengines"] = self._search_engines
            else:
                # Full replacement: include the whole engine map
                settings["url.searchengines"] = self._search_engines
            logger.debug(
                "[UserLayer] search_engines (%s): %s",
                "merge" if self._search_engines_merge else "replace",
                list(self._search_engines.keys()),
            )

        # ── Spellcheck ────────────────────────────────────────────────────
        if self._spellcheck_langs is not None:
            settings["spellcheck.languages"] = self._spellcheck_langs

        # ── Extra settings (escape hatch) ─────────────────────────────────
        if self._extra_settings:
            settings.update(self._extra_settings)
            logger.debug("[UserLayer] extra_settings keys: %s", list(self._extra_settings))

        return settings

    def _keybindings(self) -> BindingList:
        return list(self._extra_bindings)

    def _aliases(self) -> ConfigDict:
        base: ConfigDict = {
            # Permanent convenience alias — goes to user's GitHub profile
            "gh": f"open -t https://github.com/{self._github_username}",
        }
        base.update(self._extra_aliases)
        return base
