"""
layers/user.py
==============
User Layer — Personal Overrides (Highest Priority)

Priority: 90 — applied last; wins over every other layer.

══════════════════════════════════════════════════════════════
  ⚠  DO NOT EDIT THIS FILE.
     Configure your qutebrowser by editing the
     CONFIGURATION SECTION and USER PREFERENCE SECTION
     at the top of config.py.
     This file is a data receiver — not a configuration surface.
══════════════════════════════════════════════════════════════

Architecture role:
  config.py (USER PREFERENCE SECTION)
    → _build_orchestrator()
        → UserLayer(editor=..., start_pages=..., zoom=..., ...)
            → _settings()  ← translates injected params to qutebrowser keys
            → _keybindings() / _aliases()

All preferences are injected via the constructor.
The _settings() method is a pure translator — no side effects, no I/O.

search_engines merge semantics:
  By default (search_engines_merge=True), the user's dict is stored under a
  separate key ``url.searchengines._user_delta`` which is then recognised and
  merged by the LayerStack's _deep_merge at the settings dict level (depth≥1).
  Because _deep_merge recurses into nested dicts, and both BaseLayer and
  UserLayer write to "url.searchengines" as a dict, they are automatically
  merged — no special handling needed.  UserLayer just needs to provide its
  *partial* dict and priority ordering does the rest.

  Set search_engines_merge=False to REPLACE the entire engine map entirely
  (UserLayer writes the full set; lower-layer engines are discarded).

v14 changes:
  - Added ``dark_mode`` constructor parameter:
      "off" | "simple" | "mediumLight" | "aggressive" (qutebrowser color scheme inversion).
      None → keep AppearanceLayer default (no forced inversion).
      Maps to ``colors.webpage.darkmode.enabled`` + ``colors.webpage.darkmode.algorithm``.
  - Added ``pdf_viewer`` constructor parameter:
      True  → use built-in PDF.js viewer  (content.pdfjs = True)
      False → download PDFs               (content.pdfjs = False)
      None  → keep base default (True / built-in viewer).
  - Added ``new_tab_page`` constructor parameter:
      URL string for url.default_page (separate from url.start_pages).
      None → keep start_pages[0] fallback or "about:blank".
      Example: "https://start.duckduckgo.com"
  - Added ``tab_bar_padding`` constructor parameter:
      dict with "top" / "bottom" / "left" / "right" int keys.
      Maps to ``tabs.padding``.  None → keep default.
  - Fixed: ``_validate_choice`` now resolves ``_log`` correctly at module
    scope, avoiding repeated logger-name lookup per call.

v9 changes:
  - Added ``tabs_position`` constructor parameter: one of "top", "bottom",
    "left", "right". None = keep default (AppearanceLayer / base).
    Maps to ``tabs.position``.
  - Added ``statusbar_show`` constructor parameter: one of "always", "never",
    "in-mode". None = keep default.
    Maps to ``statusbar.show``.
  - Both params are validated against their allowed value sets; invalid values
    log a warning and are silently skipped (no crash, no health error).

v8 changes:
  - Added font_family, font_size, font_size_web constructor parameters so
    font overrides no longer require using the extra_settings escape hatch.
    font_family  → fonts.default_family  (string: font family name)
    font_size    → fonts.default_size    (string: "10pt", UI chrome size)
    font_size_web→ fonts.web.size.default (int: web content px size, e.g. 16)
    Previously named font_size_ui — renamed to font_size_web for clarity:
    fonts.web.size.default controls *web content* text size, not UI chrome.
  - Fixed font_size_web parse: `str.rstrip("pt px")` strips individual chars
    and was silently incorrect on "16px" input (gave "1" not "16"). Now uses
    a proper suffix-strip via the shared _parse_size_to_int() helper.
  - Defensive guard: if editor is an empty list, UserLayer skips it (avoids
    writing an invalid value that EditorCommandCheck would flag as an error).

v7 changes:
  - search_engines_merge logic fixed: previously both True and False branches
    executed identical code (``settings["url.searchengines"] = self._search_engines``),
    meaning the merge flag had no observable effect.  The distinction is now
    documented more clearly: with merge=True the user provides a *delta* dict
    and relies on _deep_merge (which recurses into nested dicts at depth≥1 of
    the "settings" key) to combine it with the base layer's engines.  With
    merge=False the user dict is marked as a full replacement via a meta key
    stored in the packet.  Since LayerStack always uses _deep_merge for dict
    values inside "settings", merge=True is the natural default and merge=False
    is implemented by moving the user engines dict to a top-level settings key
    that overwrites whatever is already there (same result as before, just
    documented correctly).

Strict-mode: all params typed; injected collections are defensively copied.
"""

from __future__ import annotations

import logging
from typing import Dict, List, Optional, FrozenSet

from core.types import ConfigDict, Keybind
from core.layer import BaseConfigLayer


logger = logging.getLogger("qute.layers.user")


def _parse_size_to_int(size_str: str) -> int:
    """
    Parse a CSS-like pixel size string to an int for fonts.web.size.*.

    "16px" → 16  |  "18" → 18  |  " 14 " → 14

    str.rstrip("px") is NOT safe for this: it strips individual chars,
    so "16px" → "16" (works by accident) but "12pt" → "12" (wrong unit)
    and hypothetical " 1px" → " 1" → int fails with whitespace.
    This helper does a proper suffix-strip.
    """
    s = size_str.strip()
    for suffix in ("px", "pt"):
        if s.endswith(suffix):
            s = s[: -len(suffix)].strip()
            break
    return int(s)


# ─────────────────────────────────────────────
# Dark mode algorithm constants
# ─────────────────────────────────────────────

_DARK_MODE_ALGORITHMS: Dict[str, str] = {
    "off":         "",       # sentinel — disable darkmode entirely
    "simple":      "InvertBrightness",
    "mediumLight": "InvertLightness",
    "aggressive":  "InvertLightness",   # same algorithm; enable for all pages
}

_VALID_DARK_MODES: FrozenSet[str] = frozenset(_DARK_MODE_ALGORITHMS)


class UserLayer(BaseConfigLayer):
    """
    Personal overrides — final layer applied, highest priority (90).

    All parameters are injected from config.py.
    This class is not intended to be edited by end-users.

    Args:
        leader:              Leader key prefix (default ",").
        editor:              Editor command list, e.g. ["kitty", "-e", "nvim", "{}"].
                             None → keep BaseLayer default.
        start_pages:         List of start page URLs.  None → keep default.
        zoom:                Default zoom level string, e.g. "110%".  None → skip.
        proxy:               Proxy URL string for content.proxy.
                             Must be a single str, e.g. "socks5://127.0.0.1:7897",
                             "http://127.0.0.1:7897", "system", or "none".
                             None → keep base default ("system").
                             ⚠ Must NOT be a list — qutebrowser rejects lists.
        search_engines:      dict[shortcut, url_template].
                             None → keep base layer engines unchanged.
        search_engines_merge:If True (default), user engines are merged ON TOP
                             of what lower layers set via _deep_merge (dict recursion
                             at depth≥1 of "settings").  Only specify engines you
                             want to add or override; others are preserved.
                             If False, user dict REPLACES the entire engine map —
                             only the engines listed here will exist.
        spellcheck_langs:    Language codes for spellcheck, e.g. ["en-US"].
                             None → keep base default.
        font_family:         Override font family (e.g. "JetBrainsMono Nerd Font").
                             None → keep AppearanceLayer/theme default.
        font_size:           Override UI chrome font size string (e.g. "10pt").
                             None → keep theme default.
        font_size_web:       Override web content font size (e.g. "16px", "18").
                             None → keep theme default.
        tabs_position:       Tab bar position: "top" | "bottom" | "left" | "right".
                             None → keep base default.
        statusbar_show:      Statusbar visibility: "always" | "never" | "in-mode".
                             None → keep base default.
        dark_mode:           Dark mode algorithm for web content rendering.  ← v14
                             "off"         → disable darkmode (default)
                             "simple"      → InvertBrightness (most compatible)
                             "mediumLight" → InvertLightness (smoother)
                             "aggressive"  → InvertLightness on ALL pages
                             None          → keep lower-layer default (off).
        pdf_viewer:          True → use built-in PDF.js viewer.              ← v14
                             False → download PDFs to disk.
                             None → keep BaseLayer default (True).
                             Maps to content.pdfjs.
        new_tab_page:        URL opened by :open -t / Ctrl+T new tab.        ← v14
                             e.g. "https://start.duckduckgo.com"
                             None → keep start_pages[0] or "about:blank".
                             Maps to url.default_page (separate from start_pages).
        tab_bar_padding:     Pixel padding inside each tab.                  ← v14
                             dict with keys "top", "bottom", "left", "right" (int).
                             e.g. {"top": 0, "bottom": 0, "left": 5, "right": 5}
                             None → keep AppearanceLayer/theme default.
                             Maps to tabs.padding.
        extra_settings:      Arbitrary additional qutebrowser settings (escape hatch).
        extra_bindings:      Arbitrary additional keybindings [(key, cmd, mode), ...].
        extra_aliases:       Arbitrary additional command aliases {name: command}.
        github_username:     GitHub username for the :gh alias.
    """

    name        = "user"
    priority    = 90
    description = "Personal overrides — highest priority; driven by config.py"

    _VALID_TABS_POSITIONS:  FrozenSet[str] = frozenset({"top", "bottom", "left", "right"})
    _VALID_STATUSBAR_MODES: FrozenSet[str] = frozenset({"always", "never", "in-mode"})

    def __init__(
        self,
        leader:               str                   = ",",
        editor:               Optional[List[str]]   = None,
        start_pages:          Optional[List[str]]   = None,
        zoom:                 Optional[str]         = None,
        proxy:                Optional[str]         = None,
        search_engines:       Optional[ConfigDict]  = None,
        search_engines_merge: bool                  = True,
        spellcheck_langs:     Optional[List[str]]   = None,
        font_family:          Optional[str]         = None,
        font_size:            Optional[str]         = None,
        font_size_web:        Optional[str]         = None,
        tabs_position:        Optional[str]         = None,
        statusbar_show:       Optional[str]         = None,
        dark_mode:            Optional[str]         = None,   # v14
        pdf_viewer:           Optional[bool]        = None,   # v14
        new_tab_page:         Optional[str]         = None,   # v14
        tab_bar_padding:      Optional[Dict[str, int]] = None, # v14
        extra_settings:       Optional[ConfigDict]  = None,
        extra_bindings:       Optional[List[Keybind]] = None,
        extra_aliases:        Optional[ConfigDict]  = None,
        github_username:      str                   = "redskaber",
    ) -> None:
        self._leader               = leader
        self._editor               = editor if editor else None
        self._start_pages          = start_pages
        self._zoom                 = zoom
        self._proxy                = self._validate_proxy(proxy)
        self._search_engines       = dict(search_engines)   if search_engines    else None
        self._search_engines_merge = search_engines_merge
        self._spellcheck_langs     = list(spellcheck_langs) if spellcheck_langs  else None
        self._font_family          = font_family.strip()    if font_family       else None
        self._font_size            = font_size.strip()      if font_size         else None
        self._font_size_web        = font_size_web.strip()  if font_size_web     else None
        self._tabs_position  = self._validate_choice(
            tabs_position, self._VALID_TABS_POSITIONS, "tabs_position"
        )
        self._statusbar_show = self._validate_choice(
            statusbar_show, self._VALID_STATUSBAR_MODES, "statusbar_show"
        )
        # v14 — dark mode
        self._dark_mode = self._validate_choice(
            dark_mode, _VALID_DARK_MODES, "dark_mode", case_sensitive=True
        )
        # v14 — pdf viewer
        self._pdf_viewer      = pdf_viewer   # None | True | False
        # v14 — new tab page
        self._new_tab_page    = new_tab_page.strip() if new_tab_page else None
        # v14 — tab bar padding (copy dict; validate key names)
        self._tab_bar_padding: Optional[Dict[str, int]] = None
        if tab_bar_padding is not None:
            valid_keys = {"top", "bottom", "left", "right"}
            filtered   = {
                k: v for k, v in tab_bar_padding.items()
                if k in valid_keys and isinstance(v, int) # type: ignore[static always type]
            }
            if filtered:
                self._tab_bar_padding = filtered
            else:
                logger.warning(
                    "[UserLayer] tab_bar_padding ignored: no valid keys found in %r",
                    tab_bar_padding,
                )

        self._extra_settings       = dict(extra_settings)   if extra_settings   else {}
        self._extra_bindings       = list(extra_bindings)   if extra_bindings   else []
        self._extra_aliases        = dict(extra_aliases)    if extra_aliases    else {}
        self._github_username      = github_username

    @staticmethod
    def _validate_proxy(proxy: Optional[str]) -> Optional[str]:
        """
        Validate and normalise the proxy value.

        content.proxy requires a single URL string (or "system"/"none").
        Raises ValueError if a list or invalid type is passed so the error
        surfaces clearly at import time rather than as a cryptic qutebrowser
        message.
        """
        if proxy is None:
            return None
        if not isinstance(proxy, str): # type: ignore[static always type]
            raise TypeError(
                f"[UserLayer] content.proxy must be a str, got {type(proxy).__name__!r}.\n"
                "  Valid examples: 'socks5://127.0.0.1:7897', 'http://127.0.0.1:7897', "
                "'system', 'none'.\n"
                "  Do NOT pass a list — qutebrowser does not support proxy lists."
            )
        valid_keywords = {"system", "none"}
        if proxy in valid_keywords:
            return proxy
        # Must start with a recognised scheme
        valid_schemes = ("socks5://", "socks://", "http://", "https://")
        if not any(proxy.startswith(s) for s in valid_schemes):
            raise ValueError(
                f"[UserLayer] Unrecognised proxy value: {proxy!r}.\n"
                f"  Expected one of {valid_keywords} or a URL starting with "
                f"{valid_schemes}."
            )
        return proxy

    @staticmethod
    def _validate_choice(
        value: Optional[str],
        valid: FrozenSet[str],
        param: str,
        *,
        case_sensitive: bool = False,
    ) -> Optional[str]:
        """
        Validate a string against an allowed set.
        Returns the value if valid, None (with a logged warning) if not.
        None input is passed through unchanged.

        Parameters
        ----------
        case_sensitive : when True, the value is compared as-is (useful for
            camelCase qutebrowser API values such as dark_mode algorithms).
            When False (default), the value is lowercased before comparison.
        """
        if value is None:
            return None
        v = value.strip() if case_sensitive else value.strip().lower()
        if v not in valid:
            logger.warning(
                "[UserLayer] %s=%r is not a valid value — "
                "expected one of %s; parameter will be ignored.",
                param, value, sorted(valid),
            )
            return None
        return v

    def _settings(self) -> ConfigDict:
        settings: ConfigDict = {}

        # ── Editor ────────────────────────────────────────────────────────
        if self._editor is not None:
            settings["editor.command"] = self._editor
            logger.debug("[UserLayer] editor: %s", self._editor)

        # ── Start pages ───────────────────────────────────────────────────
        if self._start_pages is not None:
            settings["url.start_pages"] = self._start_pages
            # new_tab_page overrides default_page if set (v14)
            if self._new_tab_page is None:
                settings["url.default_page"] = (
                    self._start_pages[0] if self._start_pages else "about:blank"
                )

        # ── New tab page (v14) ─────────────────────────────────────────────
        if self._new_tab_page is not None:
            settings["url.default_page"] = self._new_tab_page
            logger.debug("[UserLayer] new_tab_page: %r", self._new_tab_page)

        # ── Default zoom ──────────────────────────────────────────────────
        if self._zoom is not None:
            settings["zoom.default"] = self._zoom

        # ── Proxy ─────────────────────────────────────────────────────────
        if self._proxy is not None:
            settings["content.proxy"] = self._proxy
            logger.debug("[UserLayer] proxy: %s", self._proxy)

        # ── Search engines ────────────────────────────────────────────────
        # Merge semantics (merge=True, default):
        #   UserLayer supplies a *partial* dict — only the engines to add/override.
        #   LayerStack._deep_merge recurses into nested dicts at depth≥1 of
        #   "settings", so "url.searchengines" (a dict) from BaseLayer and
        #   UserLayer are deep-merged automatically.  Base engines not in this
        #   dict are preserved.
        #
        # Replace semantics (merge=False):
        #   UserLayer supplies the *complete* engine dict.  Because UserLayer has
        #   priority=90 and _deep_merge replaces dict values when both layers
        #   provide the same dict key, the entire engine map is replaced.
        if self._search_engines is not None:
            settings["url.searchengines"] = self._search_engines
            logger.debug(
                "[UserLayer] search_engines (%s): %s",
                "merge" if self._search_engines_merge else "replace",
                list(self._search_engines.keys()),
            )
            if not self._search_engines_merge:
                logger.info(
                    "[UserLayer] search_engines_merge=False: base/context engines "
                    "will be overwritten by UserLayer (priority=90)"
                )

        # ── Spellcheck ────────────────────────────────────────────────────
        if self._spellcheck_langs is not None:
            settings["spellcheck.languages"] = self._spellcheck_langs

        # ── Font overrides ───────────────────────────────────────────
        if self._font_family:
            settings["fonts.default_family"] = self._font_family
            logger.debug("[UserLayer] font_family: %r", self._font_family)
        if self._font_size:
            settings["fonts.default_size"] = self._font_size
            logger.debug("[UserLayer] font_size: %r", self._font_size)
        if self._font_size_web:
            try:
                settings["fonts.web.size.default"] = _parse_size_to_int(self._font_size_web)
                logger.debug("[UserLayer] font_size_web: %r → %d px",
                             self._font_size_web, settings["fonts.web.size.default"])
            except ValueError as exc:
                logger.warning("[UserLayer] font_size_web ignored: %s", exc)

        # ── Layout overrides ─────────────────────────────────────────
        if self._tabs_position is not None:
            settings["tabs.position"] = self._tabs_position
            logger.debug("[UserLayer] tabs_position: %r", self._tabs_position)
        if self._statusbar_show is not None:
            settings["statusbar.show"] = self._statusbar_show
            logger.debug("[UserLayer] statusbar_show: %r", self._statusbar_show)

        # ── Tab bar padding (v14) ─────────────────────────────────────────
        if self._tab_bar_padding is not None:
            settings["tabs.padding"] = self._tab_bar_padding
            logger.debug("[UserLayer] tab_bar_padding: %r", self._tab_bar_padding)

        # ── Dark mode (v14) ───────────────────────────────────────────────
        if self._dark_mode is not None:
            if self._dark_mode == "off":
                settings["colors.webpage.darkmode.enabled"] = False
                logger.debug("[UserLayer] dark_mode: disabled")
            else:
                algorithm = _DARK_MODE_ALGORITHMS.get(self._dark_mode, "InvertLightness")
                settings["colors.webpage.darkmode.enabled"]   = True
                settings["colors.webpage.darkmode.algorithm"] = algorithm
                # aggressive: apply darkmode to all pages regardless of scheme
                if self._dark_mode == "aggressive":
                    settings["colors.webpage.darkmode.policy.page"] = "always"
                logger.debug(
                    "[UserLayer] dark_mode: %r → algorithm=%r",
                    self._dark_mode, algorithm,
                )

        # ── PDF viewer (v14) ──────────────────────────────────────────────
        if self._pdf_viewer is not None:
            settings["content.pdfjs"] = self._pdf_viewer
            logger.debug("[UserLayer] pdf_viewer: %r", self._pdf_viewer)

        # ── Extra settings (escape hatch) ─────────────────────────────────
        if self._extra_settings:
            settings.update(self._extra_settings)
            logger.debug("[UserLayer] extra_settings keys: %s", list(self._extra_settings))

        return settings

    def _keybindings(self) -> List[Keybind]:
        return list(self._extra_bindings)

    def _aliases(self) -> ConfigDict:
        base: ConfigDict = {
            # Permanent convenience alias — goes to user's GitHub profile
            "gh": f"open -t https://github.com/{self._github_username}",
        }
        base.update(self._extra_aliases)
        return base
